---

ssh_known_hosts_file: "~/.ssh/known_hosts"
ssh_key_file: ".ssh/id_rsa"
digitalocean_ssh_key_name: "ansible_ssh_key"
droplets_names:
  - "{{ appname }}-app-1-test"
  - "{{ appname }}-app-2-test"
  - "db-test"
  - "lb-test"
  - "{{ appname }}-app-1-prod"
  - "{{ appname }}-app-2-prod"
  - "db-prod"
  - "lb-prod"
node_management_user: "nodemanager"
db:
  alias: "db"
  port: 3306
  admin_user: "root"
  admin_password: "{{ db_admin_password }}"
app:
  port: 8080
  context: "/"
  management:
    port: 8081
  logging_file: "/var/log/{{ appname }}-api"
  repo: "https://github.com/lgueye/{{ appname }}-root.git"
  local_project_path: "/tmp/apps/{{ appname }}-root/{{ rev }}"
  local_app_path: "/tmp/apps/{{ appname }}-root/{{ rev }}/{{ appname }}-api"
  node_target_link_path: "/opt/{{ appname }}-api"
  node_source_link_path: "/opt/java-apps/{{ appname }}-api"
  db:
    user: "{{ appname }}"
    user_password: "{{ db_user_password }}"
    name: "{{ appname }}"
    driver: "com.mysql.jdbc.Driver"
    dialect: "org.hibernate.dialect.MySQL5Dialect"
    show_sql: true

appname: "standardstack"

lb:
  port: 80
