---

ssh_known_hosts_file: "~/.ssh/known_hosts"
ssh_key_file: ".ssh/id_rsa"
digitalocean_ssh_key_name: "ansible_ssh_key"
droplets_names:
  - "{{ appname }}-app-{{ target_env }}"
  - "db-{{ target_env }}"
node_management_user: "nodemanager"
db:
  ip: "{{ groups['db'][0] }}"
  alias: "db"
  port: 3306
  admin_user: "root"
  admin_password: "{{ db_admin_password }}"
app:
  ip: "{{ groups['app'][0] }}"
  port: 8080
  management:
    port: 8081
  logging_file: "/var/log/{{ appname }}-api"
  repo: "https://github.com/lgueye/{{ appname }}-root.git"
  local_project_path: "/tmp/apps/{{ appname }}-root/{{ rev }}"
  local_app_path: "/tmp/apps/{{ appname }}-root/{{ rev }}/{{ appname }}-api"
  node_target_link_path: "/opt/{{ appname }}-api"
  node_source_link_path: "/opt/java-apps/{{ appname }}-api"
  db:
    user: "{{ appname }}"
    user_password: "{{ db_user_password }}"
    name: "{{ appname }}"
    driver: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://{{ db.ip }}:{{ db.port }}/{{ appname }}?autoReconnect=true"

appname: "standardstack"
dump_filename: "/tmp/{{ app.db.name }}-dump-{{ ansible_date_time.epoch }}.sql"

#lb:
#  port: 80
#  ip: "{{ hostvars[groups['lb'][0]]['ansible_eth0']['ipv4']['address'] }}"
