---

- name: install nginx
  apt: name="{{ item }}" state="present" update_cache="yes"
  with_items:
    - nginx

- name: unix service | wait for port to be up
  wait_for: port="{{ lb.port }}" delay="1" timeout="5"
