---

- name: register clone dir existence
  stat: path="{{ app.local_project_path }}"
  register: "target_app_stats"

- name: clone
  git: repo="{{ app.repo }}" dest="{{ app.local_project_path }}" version="{{ rev }}"
  when: target_app_stats.stat.exists == false

- name: package
  command: mvn clean package -f {{ app.local_project_path }}/pom.xml
