---
- name: "configure tests to run against lb host {{ (groups['lb'] | intersect(groups[ vars['target_env'] ]))[0] }}"
  template: src="tests.properties.j2" dest="{{ app.local_project_path }}/{{ appname }}-tests/target/classes/{{ appname }}-tests.properties"

- name: "run tests"
  shell: mvn verify -Prun-tests
  args:
    chdir: "{{ app.local_project_path }}/{{ appname }}-tests"

