---

- hosts: "localhost"
  connection: "local"
  roles:
  - "inventory"
  - "generate-initial-dataset"

- hosts: "db:&{{ target_env }}"
  remote_user: "{{ node_management_user }}"
  sudo: "yes"
  roles:
  - "apply-initial-dataset"

