---

- hosts: "db:&prod"
  remote_user: "{{ node_management_user }}"
  sudo: "yes"
  tasks:
  # Copy database dump file to remote host and restore it to database {{app.db.name}}
  - name: dump data to {{ dump_filename }}
    mysql_db: login_user="{{db.admin_user}}" login_password="{{ db.admin_password }}" name="{{ app.db.name }}" state=dump target={{ dump_filename }}

- hosts: "db:&test"
  remote_user: "{{ node_management_user }}"
  sudo: "yes"
  tasks:
   - name: Copy Remote-To-Remote (from test to prod)
     synchronize: src={{ dump_filename }} dest={{ dump_filename }}
     delegate_to: "{{ groups['db'] | intersect(groups['test']) }}"

- hosts: "db:&test"
  remote_user: "{{ node_management_user }}"
  sudo: "yes"
  tasks:
  # Copy database dump file to remote host and restore it to database {{app.db.name}}
  - name: import data from {{ dump_filename }}
    mysql_db: login_user="{{db.admin_user}}" login_password="{{ db.admin_password }}" name="{{ app.db.name }}" state=import target={{ dump_filename }}
