---

- hosts: "localhost"
  connection: "local"
  roles:
  - "generate-initial-dataset"

- hosts: "db:prod"
  remote_user: "{{ node_management_user }}"
  sudo: "yes"
  roles:
  - "apply-initial-dataset"

