---

- hosts: "localhost"
  connection: "local"
  roles:
  - "inventory"

- hosts: "!localhost"
  remote_user: "root"
  roles:
  - "security"

- hosts: "db"
  remote_user: "{{ node_management_user }}"
  become: "yes"
  roles:
  - "app-db"

- hosts: "app"
  remote_user: "{{ node_management_user }}"
  become: "yes"
  roles:
  - "java"

- hosts: "lb"
  remote_user: "{{ node_management_user }}"
  become: "yes"
  roles:
  - "lb"
