---

- hosts: "localhost"
  connection: "local"
  roles:
  - "inventory"

- hosts: "!localhost"
  remote_user: "root"
  roles:
  - { role: "security"}

- hosts: "db"
  remote_user: "{{ node_management_user }}"
  sudo: "yes"
  roles:
  - "app-db"

- hosts: "lb"
  remote_user: "{{ node_management_user }}"
  sudo: "yes"
  roles:
  - "lb"
