---

- hosts: "localhost"
  connection: "local"
  roles:
  - {role: "inventory"}
  - {role: "upgrade-db", target_db: "{{ (groups['db'] | intersect(groups['test']))[0] }}" }
  - {role: "upgrade-db", target_db: "{{ (groups['db'] | intersect(groups['prod']))[0] }}" }

