---

- hosts: "localhost"
  connection: "local"
  roles:
  - {role: "inventory"}
  - {role: "clone-app", rev: "{{ rev }}"}

- hosts: "app:&{{ target_env }}"
  remote_user: "{{ node_management_user }}"
  sudo: "yes"
  tasks:
  - name: "check if application revision {{rev}} is already deployed on the node"
    stat: path="{{ deploy_dir }}/{{ appname }}.jar"
    register: "app_already_deployed"
  - name: "check if application is running"
    shell: "netcat -z localhost {{ app.port }}"
    register: "app_running"
  roles:
  - {role: "upgrade-app",
      rev: "{{ rev }}",
      require_deployment: (app_already_deployed.rc == 0),
      require_restart: (app_running.rc == 0),
      lb_excluded_node: "{{ ansible_eth0.ipv4.address }}",
      deploy_dir: "/tmp/{{ appname }}/{{ rev }}",
      build_dir: "{{ local_app_path }}/target"}
