---
#- name: remove mysql packages
#  apt: name={{ item }} state=absent
#  with_items:
#    - mysql-client
#    - mysql-server
#    - python-mysqldb

- name: install mysql packages
  apt: name={{ item }} state=present
  with_items:
    - mysql-client
    - mysql-server
    - python-mysqldb

- name: interpolate my.cnf server configuration
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root group=root mode=0600

- name: ensure service has been restarted
  service: name=mysql state=restarted sleep="1"

